import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html
        lang="en"
        suppressHydrationWarning
        className={`${inter.variable} antialiased`}
      >
        <body className="min-h-screen w-full relative">
          <main className="relative mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
            {children}
          </main>
        </body>
      </html>
    </ViewTransitions>
  );
}
